# Deploy Django App to Azure Web App
name: "Deploy to Azure"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    - name: Prepare deployment
      run: |
        mkdir deployment
        cp -r backend/* deployment/
        if [ -d "frontend" ]; then
          cp -r frontend deployment/
        fi
        cp web.config deployment/ 2>/dev/null || true
        cp startup.txt deployment/ 2>/dev/null || true
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./deployment
